server:
  tomcat:
    basedir: /usr/local #配置临时目录
  port: 12340

spring:
  application:
    name: nacos-consumer-a
  main:
    allow-bean-definition-overriding: true


# 开启 hystrix 支持（ 熔断，降级，限流）
feign:
  hystrix:
    enabled: true


#配置ribbon，负载均衡配置
ribbon:
  ConnectionTimeout: 500
  ReadTimeout: 500





#@FeignClient 注解中的 name 或 value 属性值来设置对应的 Ribbon请求的服务方，创建 Feign 客户端的时候，同时也会创建一个名为nacos-provider-a的 Ribbon 客户端。
#针对服务进行负载配置
nacos-provider-a:
  ribbon:
      connectionTimeout: 700 #请求连接超时时间
      ReadTimeout: 700 # 请求处理的超时时间
      OkToRetryOnAllOperations: true #对所有请求都进行重试(是否所有操作都重试，若false则仅get请求重试)
      MaxAutoRetries: 1 #对当前实例的重试次数
      MaxAutoRetriesNextServer: 2 #切换实例的重试次数

#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: @nacosAddress@ #读取pom文件中的配置信息



knife4j:
  # 开启增强配置
  enable: true
  #开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    username: mqz
    password: mengqizhang
  setting:
    #    #自定义主页
    #    enableHomeCustom: true
    #    homeCustomLocation: classpath:resources/home/welcome.md
    #
    #自定义footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: Copyright  2017-2021 [蒙大拿](https://gitee.com/DemoMeng)


#配置swagger-ui 密码登陆
swagger:
  #自定义配置，是否开启swagger
  enabled: true
  info:
    title: 消费方-在线接口文档
    description: 蒙大拿
    url: http://localhost:12340/doc.html
    contact: https://github.com/DemoMeng
    version: 1.0


jwt:
  secret: Mars-Cloud
  key:
    userId: USER_ID
    token: TOKEN
    roleIdList: ROLE_ID_LIST
