server:
  tomcat:
    basedir: /usr/local #配置临时目录
  port: 12340

spring:
  application:
    name: nacos-consumer-a


#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: @nacosAddress@ #读取pom文件中的配置信息





#配置swagger-ui 密码登陆
swagger:
  production: false
  basic:
    enable: true
    username: mqz
    password: mqz
  #自定义配置，是否开启swagger
  enabled: true
  info:
    title: 消费方-在线接口文档
    description: 蒙大拿
    url: http://localhost:12340/doc.html
    contact: https://github.com/DemoMeng
    version: 1.0


jwt:
  secret: Mars-Cloud
  key:
    userId: USER_ID
    token: TOKEN
    roleIdList: ROLE_ID_LIST