server:
  tomcat:
    basedir: /usr/local #配置临时目录
  port: 12342

spring:
  application:
    name: nacos-consumer-a


#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 #读取pom文件中的配置信息