version: "3.7"
services:
  nacos-1:
    hostname: nacos-1
    image: nacos/nacos-server:latest
    container_name: nsc-1
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - NACOS_SERVERS=nacos-1:8848 #nacos-2:8848 nacos-3:8848
      # - SPRING_DATASOURCE_PLATFORM=mysql
      # - MYSQL_SERVICE_HOST=192.168.1.20
      # - MYSQL_SERVICE_DB_NAME=nacos_config
      # - MYSQL_SERVICE_PORT=3306
      # - MYSQL_SERVICE_USER=root
      # - MYSQL_SERVICE_PASSWORD=mengqizhang
    env_file:
      - nacos-hostname.env  #读取mysql的配置文件，nacos使用mysql持久化的方式
    volumes:
      - /usr/local/nacos-docker/nacos-1/:/home/nacos/logs/  # /home/nacos  是nacos-docker容器的目录， /usr/local/nacos-docker-1 是宿主机的目录
    ports:
      - "8848:8848"
      - "9555:9555"
#    networks:
#      - nacos_net
    restart: on-failure
    privileged: true

#networks:
#  nacos_net:
#    external: true
