version: "3.7"
services:
  nacos:
    image: portainer/portainer:latest
    container_name: portainer-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:9000"
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai #设置容器时区
